language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  skip_existing: true
  distributions: sdist bdist_wheel
  user: amureki
  password:
    secure: Ltt9DplFIYqsTY6f7xE5iIsd1mnygMSjiatyr1vD5ajqxCYGOBcr8ABebrli/Y0Jx1nYrM45MGfcTKvYvNsfMJwPbQkMWrlaLjIPmXRCydt+Cx/zHgFKYYuypfOh7mRhTjQb0/lw1+Vwm6joM6lvv5k4gLzTBCMubc+bMJu0KTT2fKxhr5IGn2E7GI6DIcbMg6GTzeL9n/6EFNUscEDLl693VSWZh1Q2IfmOHeOxg3HYXv+sjTR5bNiCCk3w24KxO7L5zv6naZgvg49fwdrsNzxstPOjgGAqaFqH5ro8w/F93SfIMWExQ1QeIY3mE0+kkwILABp1oE2i4Yirb24toGYHYpj2McF6y1o/jwTY917ABDtCMfw7wwMWiPun+IoJ8c4JbZ56dnTAC5hsc7inyHpduRHYzFl1ZHlD+NolKj7BOjRuAnPCMNka03sH76TWIPrBa3MZAk0RysD1Q3xrInky7gULwPNezV8eRus0X+rMq6LD0JwbHdSvikR0KD0qcohcu3NKD4m/dmzBMR5Zw3805n/UpndTs6RQgckystSEni0AMEnG5sa+tgKb1TsCAkvKYNqAGt2eAjHpl6uzS28IMItenIgv4odTSFLPJhS6YGTKG0jAsJlhcGUoeBWQh0fv8jwZU8TUcLlet/GBWubkL5deAGCNDXIkRjkS+3k=
  on:
    tags: true
    repo: amureki/statuscheck
    python: 3.6
