language: python
python:
- 3.7
install:
- pip install -U tox-travis
script:
- tox
deploy:
  provider: pypi
  skip_existing: true
  distributions: sdist bdist_wheel
  user: amureki
  password:
    secure: JTHYRODN/fAxhcEO56LCsnCcMF092UevGpl9Hk99InEM30KUbwGnOFrG2ueD2V6RsDEwJ5Jw6dSkSFQ7AQaOirdfAY5W/jSSJguqhlqe5tWDS5C174H067Yhuq4Iwfo2QSKSM3PIb5pTQmpAfqLnNa/vHkeBXtJItlPovMgzCtVHhM6yP7IvHzglrM4bY7sYF3ZJ7Fpwz5pTNV3Qvkwhr26tYAydhyCKheNusfxj/Yebls9VAGee/5+e+36A2iPpVQAqlcnrkK53+gMlqB1VHkuSxFcCXuDPWQomsscFHZMNOZ6nf130DnNKos4hYkdBEarso7iy3D3D0yjlRF9ViOr89sRNIM2iuz0ciI1WqPRyPM/d9T8DByafeurGPeexwYdftzCoJVaL8/oZwqM9EMeTSLmhvQWpgxrZeQhANX+7x3mW1PTdv+UrDJeslh/UqG45mevFVunrACINdXT/9nlVTucnH6624zb6q04wByT1Y22N3Ua0EmSt+gVmpD+NYIUJe+Vfi0ReDU15y+umSymfjtPAy30LmwykIMYcvGXCN0sHcQEs4X0pqlK3L3kN1ZXxh2fgocASngHsHhZ6Zlfq/x/N0rCE0H+1rkgBrqKMeISX4i1shN0rSEH4x7B03wEhitKrX0vof/pewTOYjivUBggVjBnbcorw0H4UaRA=
  on:
    tags: true
    repo: amureki/statuscheck
    python: 3.7
