name: Check Changelog

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.pull_request.body, '[skip changelog]') &&
      (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v1
      - name: Check that CHANGELOG is updated
        run: git diff remotes/origin/${{ github.base_ref }} --name-only | grep CHANGELOG.md
