name: PyPI release

on:
  release:
    types: [released]

jobs:
  package:
    name: Build & verify package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip setuptools wheel twine
      - name: Build dist packages
        run: python setup.py sdist bdist_wheel
      - name: Upload packages
        run: python -m twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
